---
settings:
  name: Azure Blob storage
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation sur le stockage d'objets blob Azure
    url: "/index.html"
  - title: Notes de version
    url: "/whats-new.html"
  - title: Commencer
    entries:
    - title: Afficher vos comptes de stockage Azure Blob
      url: "/task-view-azure-blob-storage.html"
  - title: Gérer les comptes de stockage Azure Blob
    entries:
    - title: Ajouter de nouveaux comptes de stockage
      url: "/task-add-blob-storage.html"
    - title: Modifier les paramètres des comptes de stockage
      url: "/task-change-blob-storage-settings.html"
    - title: Utiliser les services de données NetApp avec le stockage Azure Blob
      url: "/task-blob-enable-data-services.html"
  - title: Connaissances et soutien
    entries:
    - title: Inscrivez-vous pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenir de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
